### ISSUE TITLE
npm8.3.1编译失败

### ISSUE THREAD

**Issue by KissMyLady** [linhaojun857/aurora#149]
## 一, 软件版本
```sh
node  v18.18.0
npm   8.3.1
@vue/cli 5.0.8
```

编译命令
```sh
npm install 

npm run dev
```

## 二, 错误日志
```sh
ERROR in src/views/FriendLink.vue:47:81
TS2307: Cannot find module 'vue' or its corresponding type declarations.
    45 |
    46 | <script lang="ts">
  > 47 | import { defineComponent, reactive, provide, computed, toRefs, onMounted } from 'vue'
       |                                                                                 ^^^^^
    48 | import { useI18n } from 'vue-i18n'
    49 | import { Sidebar, Profile } from '../components/Sidebar'
    50 | import Breadcrumb from '@/components/Breadcrumb.vue'

ERROR in src/views/Home.vue:72:84
TS2307: Cannot find module 'vue' or its corresponding type declarations.
    70 |
    71 | <script lang="ts">
  > 72 | import { computed, defineComponent, onMounted, ref, toRefs, toRef, reactive } from 'vue'
       |                                                                                    ^^^^^
    73 | import { Feature, FeatureList } from '@/components/Feature'
    74 | import { ArticleCard, HorizontalArticle } from '@/components/ArticleCard'
    75 | import { Title } from '@/components/Title'

ERROR in src/views/Message.vue:23:81
TS2307: Cannot find module 'vue' or its corresponding type declarations.
    21 | </template>
    22 | <script lang="ts">
  > 23 | import { defineComponent, onMounted, reactive, toRefs, computed, provide } from 'vue'
       |                                                                                 ^^^^^
    24 | import { useI18n } from 'vue-i18n'
    25 | import { Sidebar, Profile } from '../components/Sidebar'
    26 | import Breadcrumb from '@/components/Breadcrumb.vue'

ERROR in src/views/Photos.vue:44:61
TS2307: Cannot find module 'vue' or its corresponding type declarations.
    42 | </template>
    43 | <script lang="ts">
  > 44 | import { computed, defineComponent, reactive, toRefs } from 'vue'
       |                                                             ^^^^^
    45 | import { useI18n } from 'vue-i18n'
    46 | import { useCommonStore } from '@/stores/common'
    47 | import { useRoute, onBeforeRouteUpdate } from 'vue-router'

ERROR in src/views/Tags.vue:18:64
TS2307: Cannot find module 'vue' or its corresponding type declarations.
    16 |
    17 | <script lang="ts">
  > 18 | import { defineComponent, onMounted, onUnmounted, toRef } from 'vue'
       |                                                                ^^^^^
    19 | import Breadcrumb from '@/components/Breadcrumb.vue'
    20 | import { useI18n } from 'vue-i18n'
    21 | import { useTagStore } from '@/stores/tag'

ERROR in src/views/Talk.vue:52:81
TS2307: Cannot find module 'vue' or its corresponding type declarations.
    50 |
    51 | <script lang="ts">
  > 52 | import { defineComponent, onMounted, reactive, toRefs, provide, computed } from 'vue'
       |                                                                                 ^^^^^
    53 | import { useRoute, useRouter } from 'vue-router'
    54 | import { useI18n } from 'vue-i18n'
    55 | import Breadcrumb from '@/components/Breadcrumb.vue'

ERROR in src/views/TalkList.vue:62:62
TS2307: Cannot find module 'vue' or its corresponding type declarations.
    60 |
    61 | <script lang="ts">
  > 62 | import { defineComponent, onMounted, reactive, toRefs } from 'vue'
       |                                                              ^^^^^
    63 | import { useI18n } from 'vue-i18n'
    64 | import Breadcrumb from '@/components/Breadcrumb.vue'
    65 | import { Sidebar, Profile } from '../components/Sidebar'
```

**Comment by KissMyLady** [comment]
# 在macOS上编译 aurora-blog 失败❌❌

平台信息
```sh
系统: Apple M1 13.5
node v18.18.0
npm 9.8.1
```

## 报错日志
```sh
$ npm run build

> aurora-blog@0.1.0 build
> vue-cli-service build

All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.


✔  Building for production...
 ERROR  Error: Cannot find module 'vue-template-compiler'
        Require stack:
        - /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-plugin-typescript/index.js
        - /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/lib/Service.js
        - /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/bin/vue-cli-service.js
Error: Cannot find module 'vue-template-compiler'
Require stack:
- /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-plugin-typescript/index.js
- /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/lib/Service.js
- /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/bin/vue-cli-service.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.resolve (node:internal/modules/cjs/helpers:125:19)
    at /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-plugin-typescript/index.js:87:35
    at /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/lib/Service.js:268:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/lib/Service.js:268:26)
    at PluginAPI.resolveChainableWebpackConfig (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/lib/PluginAPI.js:145:25)
    at module.exports (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/lib/commands/build/resolveAppConfig.js:9:22)
    at build (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/lib/commands/build/index.js:147:50)
    at /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/lib/commands/build/index.js:69:13
    at Service.run (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/lib/Service.js:262:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## 根据上述报错，重新安装`vue-template-compiler`

报错日志 节选
```sh
ERROR in ./src/views/TalkList.vue?vue&type=style&index=0&id=76bef0a4&lang=scss&scoped=true (./node_modules/css-loader/dist/cjs.js??clonedRuleSet-22.use[1]!./node_modules/vue-loader/dist/stylePostLoader.js!./node_modules/@vue/cli-service/node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-22.use[2]!./node_modules/sass-loader/dist/cjs.js??clonedRuleSet-22.use[3]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/views/TalkList.vue?vue&type=style&index=0&id=76bef0a4&lang=scss&scoped=true)
Module Error (from ./node_modules/sass-loader/dist/cjs.js):
Cannot find module 'sass'
Require stack:
- /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/sass-loader/dist/utils.js
- /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/sass-loader/dist/index.js
- /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/sass-loader/dist/cjs.js
- /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/webpack/lib/ProgressPlugin.js
- /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/progress-webpack-plugin/index.js
- /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/lib/commands/serve.js
- /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/lib/Service.js
- /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/bin/vue-cli-service.js
 @ ./node_modules/vue-style-loader/index.js??clonedRuleSet-22.use[0]!./node_modules/css-loader/dist/cjs.js??clonedRuleSet-22.use[1]!./node_modules/vue-loader/dist/stylePostLoader.js!./node_modules/@vue/cli-service/node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-22.use[2]!./node_modules/sass-loader/dist/cjs.js??clonedRuleSet-22.use[3]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/views/TalkList.vue?vue&type=style&index=0&id=76bef0a4&lang=scss&scoped=true 4:14-451 15:3-20:5 16:22-459
 @ ./src/views/TalkList.vue?vue&type=style&index=0&id=76bef0a4&lang=scss&scoped=true 1:0-512 1:0-512
 @ ./src/views/TalkList.vue 5:0-80
 @ ./src/router/index.ts 13:19-50
 @ ./src/main.ts 3:0-30 41:38-44

ERROR in ./src/views/TalkList.vue?vue&type=style&index=0&id=76bef0a4&lang=scss&scoped=true (./node_modules/css-loader/dist/cjs.js??clonedRuleSet-22.use[1]!./node_modules/vue-loader/dist/stylePostLoader.js!./node_modules/@vue/cli-service/node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-22.use[2]!./node_modules/sass-loader/dist/cjs.js??clonedRuleSet-22.use[3]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/views/TalkList.vue?vue&type=style&index=0&id=76bef0a4&lang=scss&scoped=true)
Module build failed (from ./node_modules/@vue/cli-service/node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS received undefined instead of CSS string
    at new Input (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/node_modules/postcss/lib/input.js:24:13)
    at parse (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/node_modules/postcss/lib/parse.js:8:15)
    at new LazyResult (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/node_modules/postcss/lib/lazy-result.js:133:16)
    at Processor.process (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/node_modules/postcss/lib/processor.js:53:14)
    at Object.loader (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/node_modules/postcss-loader/dist/index.js:97:30)
 @ ./node_modules/vue-style-loader/index.js??clonedRuleSet-22.use[0]!./node_modules/css-loader/dist/cjs.js??clonedRuleSet-22.use[1]!./node_modules/vue-loader/dist/stylePostLoader.js!./node_modules/@vue/cli-service/node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-22.use[2]!./node_modules/sass-loader/dist/cjs.js??clonedRuleSet-22.use[3]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/views/TalkList.vue?vue&type=style&index=0&id=76bef0a4&lang=scss&scoped=true 4:14-451 15:3-20:5 16:22-459
 @ ./src/views/TalkList.vue?vue&type=style&index=0&id=76bef0a4&lang=scss&scoped=true 1:0-512 1:0-512
 @ ./src/views/TalkList.vue 5:0-80
 @ ./src/router/index.ts 13:19-50
 @ ./src/main.ts 3:0-30 41:38-44

ERROR in ./src/styles/index.scss (./node_modules/css-loader/dist/cjs.js??clonedRuleSet-24.use[1]!./node_modules/@vue/cli-service/node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-24.use[2]!./node_modules/sass-loader/dist/cjs.js??clonedRuleSet-24.use[3]!./src/styles/index.scss)
Module Error (from ./node_modules/sass-loader/dist/cjs.js):
Cannot find module 'sass'
Require stack:
- /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/sass-loader/dist/utils.js
- /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/sass-loader/dist/index.js
- /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/sass-loader/dist/cjs.js
- /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/webpack/lib/ProgressPlugin.js
- /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/progress-webpack-plugin/index.js
- /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/lib/commands/serve.js
- /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/lib/Service.js
- /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/bin/vue-cli-service.js
 @ ./src/styles/index.scss 4:14-275 15:3-20:5 16:22-283
 @ ./src/main.ts 5:0-29

ERROR in ./src/styles/index.scss (./node_modules/css-loader/dist/cjs.js??clonedRuleSet-24.use[1]!./node_modules/@vue/cli-service/node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-24.use[2]!./node_modules/sass-loader/dist/cjs.js??clonedRuleSet-24.use[3]!./src/styles/index.scss)
Module build failed (from ./node_modules/@vue/cli-service/node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS received undefined instead of CSS string
    at new Input (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/node_modules/postcss/lib/input.js:24:13)
    at parse (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/node_modules/postcss/lib/parse.js:8:15)
    at new LazyResult (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/node_modules/postcss/lib/lazy-result.js:133:16)
    at Processor.process (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/node_modules/postcss/lib/processor.js:53:14)
    at Object.loader (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/node_modules/postcss-loader/dist/index.js:97:30)
 @ ./src/styles/index.scss 4:14-275 15:3-20:5 16:22-283
 @ ./src/main.ts 5:0-29
```

**Comment by KissMyLady** [comment]
# 在Mac M1上编译blog失败

系统: Apple M1 13.5
node : 18.18.0
npm : 9.8.1

执行命令
````sh
npm run build
```

错误日志
```log
 error  in css/chunk-vendors.e33e7481.css

css/chunk-vendors.e33e7481.css from Css Minimizer plugin
Error: PostCSS plugin postcss-discard-comments requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/postcss/lib/processor.js:167:15)
    at new Processor (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/postcss/lib/postcss.js:55:10)
    at cssnanoPlugin (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/cssnano/src/index.js:167:10)
    at cssnanoMinify (eval at transform (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/css-minimizer-webpack-plugin/dist/minify.js:79:28), <anonymous>:95:33)
    at minify (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/css-minimizer-webpack-plugin/dist/minify.js:37:32)
    at Object.transform (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/css-minimizer-webpack-plugin/dist/minify.js:80:10)
    at execFunction (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/jest-worker/build/workers/threadChild.js:148:17)
    at execHelper (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/jest-worker/build/workers/threadChild.js:127:5)
    at execMethod (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/jest-worker/build/workers/threadChild.js:131:5)

 ERROR  Error: Build failed with errors.
Error: Build failed with errors.
    at /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/@vue/cli-service/lib/commands/build/index.js:207:23
    at /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/webpack/lib/webpack.js:157:8
    at /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.shutdown (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/webpack/lib/Cache.js:150:23)
    at /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/webpack/lib/Compiler.js:1229:15
    at Hook.eval [as callAsync] (eval at create (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.close (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/webpack/lib/Compiler.js:1222:23)
    at /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/webpack/lib/webpack.js:156:16
    at finalCallback (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/webpack/lib/Compiler.js:441:32)
    at /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/webpack/lib/Compiler.js:458:13
    at Hook.eval [as callAsync] (eval at create (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:33:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at onCompiled (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/webpack/lib/Compiler.js:456:21)
    at /Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/webpack/lib/Compiler.js:1200:17
    at eval (eval at create (/Users/mylady/code/java/blog/aurora/aurora-vue/aurora-blog/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by XueHao-cyber** [comment]
我是amd 的处理器 ，也是报 PostCSS received undefined instead of CSS string
